CREATE INDEX `idx_futures_games_date` ON `futures_games` (`game_date`);
CREATE INDEX `idx_games_season` ON `games` (`season`);
CREATE INDEX `idx_games_home_team` ON `games` (`home_team_id`);
CREATE INDEX `idx_games_date` ON `games` (`game_date`);
CREATE INDEX `idx_games_away_team` ON `games` (`away_team_id`);
CREATE INDEX `idx_roster_team` ON `kbo_roster` (`team`);
CREATE INDEX `idx_roster_player` ON `kbo_roster` (`player_id`);
CREATE INDEX `idx_moves_player` ON `kbo_roster_moves` (`player_id`);
CREATE INDEX `idx_moves_date` ON `kbo_roster_moves` (`move_date`);
CREATE INDEX `idx_pbp_pitcher` ON `play_by_play` (`pitcher_ID`);
CREATE INDEX `idx_pbp_game` ON `play_by_play` (`gameID`);
CREATE INDEX `idx_pbp_batter` ON `play_by_play` (`batter_ID`);
CREATE INDEX `idx_pbp_game_date` ON `play_by_play` (`game_date`);
CREATE INDEX `idx_players_team` ON `players` (`team_id`);
CREATE UNIQUE INDEX `uq_stadium_dim_1` ON `stadium_dim` (`full_name`);
CREATE INDEX `idx_wpf_batter_season` ON `weighted_pf_by_batter_season` (`batter_ID`, `season`);
CREATE INDEX `idx_wrc_season` ON `wrc_plus_comparison` (`season`);
ALTER TABLE `games` ADD CONSTRAINT `fk_games_away_team_id` FOREIGN KEY (`away_team_id`) REFERENCES `teams` (`team_id`);
ALTER TABLE `games` ADD CONSTRAINT `fk_games_home_team_id` FOREIGN KEY (`home_team_id`) REFERENCES `teams` (`team_id`);
ALTER TABLE `players` ADD CONSTRAINT `fk_players_team_id` FOREIGN KEY (`team_id`) REFERENCES `teams` (`team_id`);
